services:
  - type: web
    name: nitmz-campus-bus-server
    runtime: node
    region: singapore
    plan: free
    rootDir: my_server
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        sync: false
      - key: API_SECRET_KEY
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_SSL
        sync: false
    healthCheckPath: /
